### ISSUE TITLE
Changing a remote's Git URL doesn't update the cache

### ISSUE THREAD

**Issue by ekohl** [xorpaul/g10k#185]
Consider the following config
```yaml
cachedir: '/var/cache/g10k'

sources:
  control:
    remote: 'https://example.com/my-git-repo'
    basedir: '/var/lib/g10k/environments'
```

Then I run g10k. This does what I want and we can see that:
```console
# git -C /var/cache/g10k/environments/control.git remote -v
origin	https://example.com/my-git-repo (fetch)
origin	https://example.com/my-git-repo (push)
```

However, now my git repo URL changes:
```yaml
cachedir: '/var/cache/g10k'

sources:
  control:
    remote: 'https://git.example.com/my-git-repo'
    basedir: '/var/lib/g10k/environments'
```

Again, I run g10k. This exits successfully. However, the code isn't updated. This is because the cache still points to the same remote.

```console
# git -C /var/cache/g10k/environments/control.git remote -v
origin	https://example.com/my-git-repo (fetch)
origin	https://example.com/my-git-repo (push)
```

Removing `control.git` and running g10k again does result in a correct git remote.
