### ISSUE TITLE
syncing multiple git sources with same branches fails

### ISSUE THREAD

**Issue by juliantaylor** [xorpaul/g10k#220]
syncing multiple git sources with the same branch does not work anymore probably since strip_components was added:

```
sources:
  hiera:
    remote: 'gitb' 
    basedir: '/opt/puppetlabs/code/g10kstaging/hiera'
  filestore:
    remote: 'gita' 
    basedir: '/opt/puppetlabs/code/g10kstaging/filestore/'

```

gita and gitb contain the same branches and no puppetfile.

This then fails despite no renaming happening at all:

```
g10k -config config.yaml -info
Renamed environment naming conflict detected with renamed environment master
```

this used to work fine in version 0.8.9
