### ISSUE TITLE
g10k fails on some yaml configs that are valid and work with r10k

### ISSUE THREAD

**Issue by gdubicki** [xorpaul/g10k#41]
g10k fails to parse the following config correctly:

```
---
:cachedir: '/var/cache/r10k'
:sources:
  :hieradata:
    remote: git@git.mydomain.com:puppet/hiera.git
    basedir: /etc/puppet/hieradata
  :envs:
    remote: git@git.mydomain.com:puppet/envs.git
    basedir: /etc/puppet/environments
```

...with the following output:

```
Synced /etc/puppetlabs/r10k/r10k.yaml with 0 git repositories and 0 Forge modules in 0.0s with git (0.0s sync, I/O 0.0s) and Forge (0.0s query+download, I/O 0.0s)
```

That config with removed some of `:`s, like this:

```
---
cachedir: '/var/cache/r10k'
sources:
  hieradata:
    remote: git@git.mydomain.com:puppet/hiera.git
    basedir: /etc/puppet/hieradata
  envs:
    remote: git@git.mydomain.com:puppet/envs.git
    basedir: /etc/puppet/environments
```

...works correctly in g10k.

Note that the first one is valid YAML, according to http://www.yamllint.com/ AND is correctly parsed by r10k.

Of course it was easy to resolve, but it was not so easy to come up with the reason g10k is not working, so perhaps it's worth to do something about it.
