### ISSUE TITLE
Add option to fail on control repo unreachable

### ISSUE THREAD

**Issue by andrewfraley** [xorpaul/g10k#66]
I didn't see a way to configure this, but if the control repo is unreachable for whatever reason, invalid auth, network, etc., g10k exits 0 with:

> WARN: git repository https://myserver/org/r10k.git does not exist or is unreachable at this moment!

I'd like to fail in that case and exit 1.

**Comment by xorpaul** [comment]
Fixed with https://github.com/xorpaul/g10k/releases/tag/v0.3.9 https://github.com/xorpaul/g10k/commit/f26bfa6511d4a4ede7455127b2670ad3bdda8e99

From the README.md

#### abort g10k run if source repository is unreachable

```
---
:cachedir: '/tmp/g10k'

sources:
  example:
    remote: 'git://github.com/xorpaul/g10k-environment-unavailable.git'
    basedir: '/tmp/example/'
    exit_if_unreachable: true
```

If you then call g10k with that config file. You should get:

```
WARN: git repository git://github.com/xorpaul/g10k-environment-unavailable.git does not exist or is unreachable at this moment!
WARNING: Could not resolve git repository in source 'example' (git://github.com/xorpaul/g10k-environment-unavailable.git)
```
with an exit code 1
