### ISSUE TITLE
Puppetfile option with a config file

### ISSUE THREAD

**Issue by mchouque** [xorpaul/g10k#71]
Hello,

This issue is somewhat related to issue #70 where with r10k, I can have both a simple config file and still use: *puppetfile install*.

My yaml config (r10k.yaml) file contains:
```
---
cachedir: /tmp/somerandomdirectory
forge: {baseurl: 'http://myforge:42080'}
git:
    private_key: /home/user/.ssh/id_rsa
    provider: rugged
```

And I run r10k with the following options (which works properly):
```
r10k -c r10k.yaml puppetfile install -v info --puppetfile Puppetfile --moduledir modules
```

If I try the same thing with g10k, I get this message "*-puppetfile parameter is not allowed with -config parameter*" which is different from what r10k supports: is there a reason for that?

So either:
* I figure out how to write a full file based configuration using my Puppetfile (so far I haven't haha)
* or like with #70, provide a way to set more than just cachedir
* or support a config file with -puppetfile parameter

Cheers,
Mathieu
