### ISSUE TITLE
check for available git version

### ISSUE THREAD

**Issue by xorpaul** [xorpaul/g10k#95]
Testing g10k 0.4.5, which worked on CentOS 7, but I had to roll it back on CentOS 6.
I believe the problem is some incompatibility with the version of git available on CentOS 6.
This is the error that I get:
```
Executing git --git-dir /opt/puppetlabs/g10k/cache/ssh-__gitlab@gitlab.example.net_puppet-apps_perfui rev-parse --verify 'test^{object}' took 0.02260s
executeCommand(): git command failed: git --git-dir /opt/puppetlabs/g10k/cache/ssh-__gitlab@gitlab.example.net_puppet-apps_perfui rev-parse --verify 'test^{object}' exit status 128
Output: fatal: Needed a single revision
```

CentOS 6:

```
# git --version
git version 1.7.1
```
CentOS 7:
```
# git --version
git version 1.8.3.1

**Comment by xorpaul** [comment]
Added documentation for new g10k config setting:

To check for really existing objects, g10k uses `master^{object}` syntax, which is not supported in older Git versions, like on CentOS 6, see [#91](https://github.com/xorpaul/g10k/issues/91) 
g10k will skip this sanity check when the g10k config setting `git_object_syntax_not_supported` is set to `true` (defaults to `false`)
Example:
```
---
:cachedir: '/tmp/g10k'
git_object_syntax_not_supported: true

sources:
  example:
    remote: 'https://github.com/xorpaul/g10k-environment.git'
    basedir: '/tmp/example/'
```
